### ISSUE TITLE
Download text from pages

### ISSUE THREAD

**Issue by clubby789** [clubby789/homestuck-downloader#1]
I would like to find an efficient way of scraping each page for text and embedding it into a lightweight HTML file. Also would like to find a way to download the [S] page javascript.

**Comment by Snigelson** [comment]
Are there any pages with JavaScript? I will primarily look into preserving the formatting of text, including inline pictures (for example [page 4081](https://www.homestuck.com/story/4081), [page 3227](https://www.homestuck.com/story/3227)), then extending the image downloading section to check for flash animations.

**Comment by clubby789** [comment]
I _believe_ Viz is in the process of converting the original flash animations into JS

**Comment by Snigelson** [comment]
That's even better!
