### ISSUE TITLE
Blocked by site

### ISSUE THREAD

**Issue by Stephenszc** [clubby789/homestuck-downloader#8]
I tried to run the script a couple of different times (it needed some tuning to do what I wanted) and then the site just kind of blocked all communications and I can't see any of it. My requests are all completely blocked when I try to run the script now and I have incomplete pieces of everything. 

That said, is there any way that you could simply upload the output the script should give? I primarily want a corpus of the text for predictive text generation, but the images may be useful to other users.

**Comment by clubby789** [comment]
I haven't touched this project in a while, but I imagine the migration to the new site has broken this script entirely. Since the format is a bit more standardised now, I might go back and rewrite this. As for the content, I'll see if I can find it anywhereon my PC

**Comment by clubby789** [comment]
I just ran this again, seems to work alright for 2000 or so pages, but a rate limiter kicks in. I'll add a link to the first 2400 pages of text that seem to have downloaded correctly in the README

**Comment by clubby789** [comment]
https://github.com/clubby789/homestuck-downloader/blob/master/text.7z
